name: Tawa veröffentlichen

on:
  workflow_dispatch:
  push:
    branches: [ haupt ]
  pull_request:
    branches: [ haupt ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Tawa kompilieren
    steps:
    - name: Repository auschecken
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt update -yy
        sudo apt install -yy --no-install-recommends upx
    - name: Go herunterladen
      uses: actions/setup-go@v2
      with:
        go-version: '^1.16.6'
    - name: Tawa kompilieren
      run: |
        go build -ldflags="-s -w"
    - name: Mit UPX packieren
      run: |
        upx Tawa
    - name: Release hochladen
      if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          wget -q https://github.com/TheAssassin/pyuploadtool/releases/download/continuous/pyuploadtool-x86_64.AppImage
          chmod +x pyuploadtool-x86_64.AppImage
          ./pyuploadtool-x86_64.AppImage Tawa
